# Word choice

I recommend trying to replace Latin-derived words and phrases 
with Old English-derived equivalents (["Anglish"](https://anglish.org/) words) 
where possible; 
it generally makes writing simpler and easier to read.
Latin words 
<!-- often have elitist overtones, and -->
create artificial barriers to understanding.
Many Latin-derived words commonly used in scientific writing
are composed from roots and affixes which are not commonly used
in their basic forms; 
hence, readers cannot determine the meanings of these words by decomposing them.
Instead, they need to memorize the meanings of these words directly.
In contrast, 
the components of composite Anglish words are typically also used individually,
so the meanings of the composites can be derived directly.
@tbl-latin-anglish-synonyms lists some common Latinate words and phrases
and Anglish alternatives.

:::{#tbl-latin-anglish-synonyms}

Latin | Anglish
----- | ------
prior to | before
necessary | needed

Commonly used Latin words and phrases and Anglish alternatives

:::


See also <https://bark-fa.github.io/Anglish-Translator/>

I am aware that this book, 
and even this chapter,
contains many Latin word choices where there are Anglish alternatives.
It is a work in progress,
and also,
I am not advocating 100% Anglish purity.
Use whichever words and phrases you think your readers are most likely
to understand easily.
Preferring Anglish is merely a useful heuristic to help achieve
our ultimate goal of producing clear, easy-to-read writing.

Just to be clear,
although I prefer Anglish words,
I have no particular preference for Anglish people or culture;
it is only a practical consideration,
based on the realities of English as the current default language of science
and the relatively-recent hybridization of the English language.
