name: Summarize new issues

on:
  issues:
    types: [opened]

jobs:
  summary:
    permissions:
      issues: write
      models: read
      contents: read
    uses: d-morrison/gha/.github/workflows/summary.yml@v1
